/**
 * build-favicon-set-core - pure PWA favicon-set logic (HTML <head> snippet
 * builder, site.webmanifest JSON builder, size/output plan, and the
 * rsvg-convert / ImageMagick argv builders) plus a spawn orchestrator.
 * ZERO harness imports (node stdlib + global only). Source of truth for the
 * pi adapter (../build-favicon-set.ts) and the Claude Code MCP toolkit
 * (../../../.claude/mcp/toolkit.ts).
 *
 * Tooling: rsvg-convert (SVG->PNG rasterization) + ImageMagick `magick`
 * (PNG->ICO multi-res, PNG resizing, transparent background).
 *
 * Extracted from build-favicon-set.ts (2026-08-12); see
 * .pi/agent/docs/pi-to-claude-code-port.md.
 */

import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import { isAbsolute, resolve as pathResolve } from "node:path";
import { tmpdir } from "node:os";

const CMD_TIMEOUT_MS = 20_000;

// -- pure: path helpers ------------------------------------------------------

export function abs(cwd: string, p: string): string {
  return isAbsolute(p) ? p : pathResolve(cwd, p);
}

export function tmpFile(ext: string): string {
  return pathResolve(tmpdir(), `pi-favicon-${randomBytes(6).toString("hex")}.${ext}`);
}

// -- pure: argv builders -----------------------------------------------------

// rsvg-convert: rasterize an SVG file to a square PNG of `size` px.
export function svgToPngArgs(svgPath: string, size: number, outPath: string): string[] {
  return ["-w", String(size), "-h", String(size), "-o", outPath, svgPath];
}

// ImageMagick: resize an existing raster to a square `size` px, transparent
// padding, centered (preserves aspect + transparency).
export function pngResizeArgs(srcPath: string, size: number, outPath: string): string[] {
  return [
    srcPath,
    "-resize", `${size}x${size}`,
    "-background", "none",
    "-gravity", "center",
    "-extent", `${size}x${size}`,
    outPath,
  ];
}

// ImageMagick: assemble a multi-resolution .ico from several PNGs.
export function buildIcoArgs(pngFiles: string[], outIcoPath: string): string[] {
  return [...pngFiles, outIcoPath];
}

// ImageMagick: maskable PWA icon - content scaled to ~80% (410px) of a 512px
// canvas with transparent safe-zone padding so the OS can crop a squircle.
export function maskableArgs(srcPng: string, outPath: string): string[] {
  return [
    srcPng,
    "-resize", "410x410",
    "-background", "none",
    "-gravity", "center",
    "-extent", "512x512",
    outPath,
  ];
}

// -- pure: HTML + manifest snippets ------------------------------------------

export function htmlSnippet(name: string): string {
  return [
    `<!-- favicons (generated by build_favicon_set) -->`,
    `<link rel="icon" href="/${name}.ico" sizes="any">`,
    `<link rel="icon" href="/${name}.svg" type="image/svg+xml">`,
    `<link rel="icon" type="image/png" sizes="16x16" href="/${name}-16.png">`,
    `<link rel="icon" type="image/png" sizes="32x32" href="/${name}-32.png">`,
    `<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`,
    `<link rel="manifest" href="/site.webmanifest">`,
  ].join("\n");
}

export function manifestJson(opts: {
  name: string;
  shortName: string;
  themeColor: string;
  backgroundColor: string;
}): string {
  return JSON.stringify(
    {
      name: opts.name,
      short_name: opts.shortName,
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        { src: "/icon-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      ],
      theme_color: opts.themeColor,
      background_color: opts.backgroundColor,
      display: "standalone",
    },
    null,
    2,
  );
}

// -- pure: the size/output plan ----------------------------------------------

export interface SizeEntry {
  size: number;
  out: string;
  /** false = temp file used only for ICO assembly, not part of the kept set */
  keep: boolean;
}

// Deterministic list of raster sizes to emit. The 48px entry is a temp file
// consumed by the .ico assembly and not part of the final artifact set.
export function planSizes(outDir: string, name: string, ico48Path: string): SizeEntry[] {
  return [
    { size: 16, out: pathResolve(outDir, `${name}-16.png`), keep: true },
    { size: 32, out: pathResolve(outDir, `${name}-32.png`), keep: true },
    { size: 48, out: ico48Path, keep: false },
    { size: 180, out: pathResolve(outDir, "apple-touch-icon.png"), keep: true },
    { size: 192, out: pathResolve(outDir, "icon-192.png"), keep: true },
    { size: 512, out: pathResolve(outDir, "icon-512.png"), keep: true },
  ];
}

// Pure: the human-readable "generated files" list for the final report.
export function generatedList(name: string, hadSvg: boolean): string[] {
  return [
    `${name}.ico (multi-res 16/32/48)`,
    `${name}-16.png`,
    `${name}-32.png`,
    `apple-touch-icon.png (180x180)`,
    `icon-192.png`,
    `icon-512.png`,
    `icon-maskable.png (512x512, 80% safe-zone)`,
    `site.webmanifest`,
    ...(hadSvg ? [`${name}.svg`] : []),
  ];
}

// Pure: assemble the final success text (report + fenced HTML snippet).
export function renderReport(outDir: string, generated: string[], snippet: string): string {
  return (
    `Built favicon set in ${outDir}:\n\n` +
    `${generated.map((g) => `  - ${g}`).join("\n")}\n\n` +
    `HTML <head> snippet:\n\n\`\`\`html\n${snippet}\n\`\`\``
  );
}

// -- spawn helper ------------------------------------------------------------

export async function run(
  cmd: string,
  args: string[],
  input?: Buffer | string,
): Promise<{ code: number; stdout: Buffer; stderr: string }> {
  return new Promise((res) => {
    let proc: ReturnType<typeof spawn>;
    try {
      proc = spawn(cmd, args, { stdio: ["pipe", "pipe", "pipe"] });
    } catch (err) {
      res({ code: 127, stdout: Buffer.alloc(0), stderr: `${(err as Error).message}` });
      return;
    }
    const chunks: Buffer[] = [];
    let stderr = "";
    const timer = setTimeout(() => proc.kill("SIGKILL"), CMD_TIMEOUT_MS);
    proc.stdout?.on("data", (d) => chunks.push(Buffer.from(d)));
    proc.stderr?.on("data", (d) => {
      stderr += d.toString();
    });
    proc.on("error", (err) => {
      clearTimeout(timer);
      res({ code: 127, stdout: Buffer.concat(chunks), stderr: `${stderr}\n${err.message}` });
    });
    proc.on("close", (code) => {
      clearTimeout(timer);
      res({ code: code ?? 1, stdout: Buffer.concat(chunks), stderr });
    });
    if (input !== undefined) {
      proc.stdin?.write(input);
      proc.stdin?.end();
    } else {
      proc.stdin?.end();
    }
  });
}

// -- harness-agnostic orchestrator -------------------------------------------

export interface FaviconResult {
  text: string;
  details: Record<string, unknown>;
  isError?: boolean;
}

export interface FaviconOpts {
  svg?: string;
  pngPath?: string;
  outDir: string;
  cwd: string;
  name?: string;
  manifestName?: string;
  manifestShortName?: string;
  themeColor?: string;
  backgroundColor?: string;
}

// Pure: validate mutually-exclusive source inputs. Returns an error string or
// null. Exported for unit testing.
export function validateSource(opts: { svg?: string; pngPath?: string }): string | null {
  if (!opts.svg && !opts.pngPath) return "Either `svg` or `pngPath` must be provided.";
  if (opts.svg && opts.pngPath) return "Pass either `svg` OR `pngPath`, not both.";
  return null;
}

export async function buildFaviconSet(opts: FaviconOpts): Promise<FaviconResult> {
  const srcErr = validateSource(opts);
  if (srcErr) return { isError: true, text: srcErr, details: {} };

  const outDir = abs(opts.cwd, opts.outDir);
  const name = opts.name ?? "favicon";
  const manifestName = opts.manifestName ?? "App";
  await mkdir(outDir, { recursive: true });

  const masterPng = pathResolve(outDir, "_master.png");
  let svgPath: string | null = null;

  try {
    if (opts.svg) {
      svgPath = pathResolve(outDir, `${name}.svg`);
      await writeFile(svgPath, opts.svg, "utf8");
      const r = await run("rsvg-convert", svgToPngArgs(svgPath, 512, masterPng));
      if (r.code !== 0) {
        return { isError: true, text: `rsvg-convert exit ${r.code}: ${r.stderr.trim()}`, details: {} };
      }
    } else {
      const src = abs(opts.cwd, opts.pngPath!);
      const r = await run("magick", pngResizeArgs(src, 512, masterPng));
      if (r.code !== 0) {
        return { isError: true, text: `magick resize exit ${r.code}: ${r.stderr.trim()}`, details: {} };
      }
    }

    const ico48Path = tmpFile("png");
    const sizes = planSizes(outDir, name, ico48Path);
    const errs: string[] = [];
    for (const { size, out } of sizes) {
      const r = svgPath
        ? await run("rsvg-convert", svgToPngArgs(svgPath, size, out))
        : await run("magick", pngResizeArgs(masterPng, size, out));
      if (r.code !== 0) errs.push(`${size}px: exit ${r.code}: ${r.stderr.trim()}`);
    }
    if (errs.length) return { isError: true, text: errs.join("\n"), details: {} };

    // Multi-res .ico from 16/32/48
    const icoR = await run("magick", buildIcoArgs([sizes[0]!.out, sizes[1]!.out, ico48Path], pathResolve(outDir, `${name}.ico`)));
    if (icoR.code !== 0) {
      return { isError: true, text: `magick ico exit ${icoR.code}: ${icoR.stderr.trim()}`, details: {} };
    }

    // Maskable PWA icon
    const maskR = await run("magick", maskableArgs(masterPng, pathResolve(outDir, "icon-maskable.png")));
    if (maskR.code !== 0) {
      return { isError: true, text: `magick maskable exit ${maskR.code}: ${maskR.stderr.trim()}`, details: {} };
    }

    await unlink(ico48Path).catch(() => {});

    // Manifest
    const manifest = manifestJson({
      name: manifestName,
      shortName: opts.manifestShortName ?? manifestName,
      themeColor: opts.themeColor ?? "#000000",
      backgroundColor: opts.backgroundColor ?? "#ffffff",
    });
    await writeFile(pathResolve(outDir, "site.webmanifest"), manifest, "utf8");

    const snippet = htmlSnippet(name);
    const generated = generatedList(name, Boolean(svgPath));

    return {
      text: renderReport(outDir, generated, snippet),
      details: { outDir, files: generated.length, name, snippet },
    };
  } finally {
    await unlink(masterPng).catch(() => {});
  }
}
