/**
 * build_favicon_set — generate the full PWA favicon artifact set from a
 * single SVG or high-res PNG source.
 *
 * Inputs: an SVG string OR a path to a high-res PNG (recommended ≥512×512).
 *
 * Outputs (written to `outDir`):
 *   - favicon.ico      — multi-resolution .ico (16, 32, 48 px)
 *   - favicon-16.png   — for legacy <link rel="icon" sizes="16x16">
 *   - favicon-32.png   — for <link rel="icon" sizes="32x32">
 *   - apple-touch-icon.png  — 180×180 for iOS home screen
 *   - icon-192.png     — PWA manifest icon
 *   - icon-512.png     — PWA manifest icon
 *   - icon-maskable.png — 512×512 maskable variant for adaptive icons
 *   - site.webmanifest — PWA manifest stub
 *   - favicon.svg      — original SVG if input was SVG
 *
 * The tool also returns an HTML `<head>` snippet ready to paste into a layout.
 *
 * Tooling: rsvg-convert (SVG→PNG rasterization) + ImageMagick `magick`
 * (PNG→ICO multi-res, PNG resizing, transparent background). Both pre-checked
 * as installed on this machine.
 *
 * Companion skill: `favicons-and-icons`.
 */

import { Type } from "@earendil-works/pi-ai";
import { defineTool, type ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "child_process";
import { mkdir, readFile, unlink, writeFile } from "fs/promises";
import { isAbsolute, resolve } from "path";
import { tmpdir } from "os";
import { randomBytes } from "crypto";

const CMD_TIMEOUT_MS = 20_000;

// ── helpers ───────────────────────────────────────────────────────────────

async function run(cmd: string, args: string[], input?: Buffer | string): Promise<{ code: number; stdout: Buffer; stderr: string }> {
  return new Promise((res) => {
    const proc = spawn(cmd, args, { stdio: ["pipe", "pipe", "pipe"] });
    const chunks: Buffer[] = [];
    let stderr = "";
    const timer = setTimeout(() => proc.kill("SIGKILL"), CMD_TIMEOUT_MS);
    proc.stdout.on("data", (d) => chunks.push(Buffer.from(d)));
    proc.stderr.on("data", (d) => {
      stderr += d.toString();
    });
    proc.on("error", (err) => {
      clearTimeout(timer);
      res({ code: 1, stdout: Buffer.concat(chunks), stderr: `${stderr}\n${err.message}` });
    });
    proc.on("close", (code) => {
      clearTimeout(timer);
      res({ code: code ?? 1, stdout: Buffer.concat(chunks), stderr });
    });
    if (input !== undefined) {
      proc.stdin.write(input);
      proc.stdin.end();
    } else {
      proc.stdin.end();
    }
  });
}

function tmpFile(ext: string): string {
  return resolve(tmpdir(), `pi-favicon-${randomBytes(6).toString("hex")}.${ext}`);
}

function abs(cwd: string, p: string): string {
  return isAbsolute(p) ? p : resolve(cwd, p);
}

// Rasterize SVG to PNG at given size via rsvg-convert.
async function svgToPng(svgPath: string, size: number, outPath: string): Promise<string | null> {
  const r = await run("rsvg-convert", ["-w", String(size), "-h", String(size), "-o", outPath, svgPath]);
  if (r.code !== 0) return `rsvg-convert exit ${r.code}: ${r.stderr.trim()}`;
  return null;
}

// Resize an existing PNG with ImageMagick. Preserves transparency.
async function pngResize(srcPath: string, size: number, outPath: string): Promise<string | null> {
  const r = await run("magick", [srcPath, "-resize", `${size}x${size}`, "-background", "none", "-gravity", "center", "-extent", `${size}x${size}`, outPath]);
  if (r.code !== 0) return `magick resize exit ${r.code}: ${r.stderr.trim()}`;
  return null;
}

// Build a multi-resolution .ico (16, 32, 48). magick handles this natively.
async function buildIco(pngFiles: string[], outIcoPath: string): Promise<string | null> {
  const r = await run("magick", [...pngFiles, outIcoPath]);
  if (r.code !== 0) return `magick ico exit ${r.code}: ${r.stderr.trim()}`;
  return null;
}

// Make a "maskable" PNG with a safe-zone-padded composite. PWA maskable icons
// need padding so the OS can crop a circle/squircle without clipping the mark.
// Convention: scale content to ~80% of canvas, transparent padding around.
async function makeMaskable(srcPng: string, outPath: string): Promise<string | null> {
  // 512px canvas, content scaled to 410px (~80%), centered, transparent bg.
  const r = await run("magick", [
    srcPng,
    "-resize", "410x410",
    "-background", "none",
    "-gravity", "center",
    "-extent", "512x512",
    outPath,
  ]);
  if (r.code !== 0) return `magick maskable exit ${r.code}: ${r.stderr.trim()}`;
  return null;
}

// ── HTML + manifest snippets ──────────────────────────────────────────────

function htmlSnippet(name: string): string {
  return [
    `<!-- favicons (generated by build_favicon_set) -->`,
    `<link rel="icon" href="/${name}.ico" sizes="any">`,
    `<link rel="icon" href="/${name}.svg" type="image/svg+xml">`,
    `<link rel="icon" type="image/png" sizes="16x16" href="/${name}-16.png">`,
    `<link rel="icon" type="image/png" sizes="32x32" href="/${name}-32.png">`,
    `<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`,
    `<link rel="manifest" href="/site.webmanifest">`,
  ].join("\n");
}

function manifestJson(opts: { name: string; shortName: string; themeColor: string; backgroundColor: string }): string {
  return JSON.stringify(
    {
      name: opts.name,
      short_name: opts.shortName,
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        { src: "/icon-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      ],
      theme_color: opts.themeColor,
      background_color: opts.backgroundColor,
      display: "standalone",
    },
    null,
    2,
  );
}

// ── tool ──────────────────────────────────────────────────────────────────

const buildFaviconSetTool = defineTool({
  name: "build_favicon_set",
  label: "Build Favicon Set",
  promptSnippet:
    "build_favicon_set — turn an SVG string or high-res PNG into a full PWA favicon set (favicon.ico multi-res + apple-touch + 192/512/maskable + site.webmanifest + HTML snippet).",
  promptGuidelines: [
    "Use build_favicon_set after writing an SVG inline or generating a 512+px PNG. Don't manually run rsvg-convert/magick — this tool encapsulates the full PWA artifact set.",
    "Prefer SVG input over PNG when the design is vector-friendly (favicons, geometric marks, monograms) — quality is better at 16/32px sizes than downscaling a raster.",
    "Output directory should usually be `public/` or `static/` of a web project. The HTML snippet returned goes in <head>.",
  ],
  description: [
    "Build the full PWA favicon artifact set from a single SVG or high-res PNG source.",
    "",
    "Pass EITHER `svg` (SVG source string) OR `pngPath` (path to a PNG, ideally ≥512×512). SVG is preferred for vector-friendly designs (cleaner at 16/32px).",
    "",
    "Writes to `outDir`:",
    "- favicon.ico (multi-res 16/32/48)",
    "- favicon-16.png, favicon-32.png",
    "- apple-touch-icon.png (180×180)",
    "- icon-192.png, icon-512.png (PWA)",
    "- icon-maskable.png (512×512 with 80% safe-zone padding)",
    "- site.webmanifest (PWA manifest stub)",
    "- favicon.svg (if input was SVG)",
    "",
    "Returns an HTML <head> snippet ready to paste into a layout.",
  ].join("\n"),
  parameters: Type.Object({
    svg: Type.Optional(Type.String({ description: "SVG source string. Mutually exclusive with pngPath." })),
    pngPath: Type.Optional(
      Type.String({ description: "Path to high-res PNG (≥512×512 ideal). Mutually exclusive with svg." }),
    ),
    outDir: Type.String({ description: "Output directory (absolute or relative to cwd, e.g. 'public' or 'static')" }),
    name: Type.Optional(Type.String({ description: "Filename prefix for favicon.ico/svg/-16/-32 (default: 'favicon')" })),
    manifestName: Type.Optional(
      Type.String({ description: "App name for site.webmanifest (default: 'App')" }),
    ),
    manifestShortName: Type.Optional(
      Type.String({ description: "Short name for site.webmanifest (default: same as manifestName, max 12 chars recommended)" }),
    ),
    themeColor: Type.Optional(Type.String({ description: "PWA theme color (default: '#000000')" })),
    backgroundColor: Type.Optional(Type.String({ description: "PWA background color (default: '#ffffff')" })),
  }),
  async execute(_id, params, _signal, _onUpdate, ctx) {
    if (!params.svg && !params.pngPath) {
      return {
        isError: true,
        content: [{ type: "text", text: "Either `svg` or `pngPath` must be provided." }],
        details: {},
      };
    }
    if (params.svg && params.pngPath) {
      return {
        isError: true,
        content: [{ type: "text", text: "Pass either `svg` OR `pngPath`, not both." }],
        details: {},
      };
    }

    const outDir = abs(ctx.cwd, params.outDir);
    const name = params.name ?? "favicon";
    const manifestName = params.manifestName ?? "App";
    await mkdir(outDir, { recursive: true });

    // Source PNG (512×512) is the canonical master we downscale from.
    const masterPng = resolve(outDir, "_master.png");
    let svgPath: string | null = null;

    try {
      if (params.svg) {
        // Write SVG to outDir + rasterize master at 512px
        svgPath = resolve(outDir, `${name}.svg`);
        await writeFile(svgPath, params.svg, "utf8");
        const err = await svgToPng(svgPath, 512, masterPng);
        if (err) {
          return { isError: true, content: [{ type: "text", text: err }], details: {} };
        }
      } else {
        // Resize source PNG to 512 master
        const src = abs(ctx.cwd, params.pngPath!);
        const err = await pngResize(src, 512, masterPng);
        if (err) {
          return { isError: true, content: [{ type: "text", text: err }], details: {} };
        }
      }

      // Generate all sized PNGs from master
      const sizes: Array<{ size: number; out: string }> = [
        { size: 16, out: resolve(outDir, `${name}-16.png`) },
        { size: 32, out: resolve(outDir, `${name}-32.png`) },
        { size: 48, out: tmpFile("png") }, // for ICO assembly, not kept
        { size: 180, out: resolve(outDir, "apple-touch-icon.png") },
        { size: 192, out: resolve(outDir, "icon-192.png") },
        { size: 512, out: resolve(outDir, "icon-512.png") },
      ];
      const errs: string[] = [];
      const ico48Path = sizes[2]!.out;
      for (const { size, out } of sizes) {
        const e = svgPath ? await svgToPng(svgPath, size, out) : await pngResize(masterPng, size, out);
        if (e) errs.push(`${size}px: ${e}`);
      }
      if (errs.length) {
        return { isError: true, content: [{ type: "text", text: errs.join("\n") }], details: {} };
      }

      // Build multi-res .ico from 16/32/48
      const icoErr = await buildIco(
        [sizes[0]!.out, sizes[1]!.out, ico48Path],
        resolve(outDir, `${name}.ico`),
      );
      if (icoErr) {
        return { isError: true, content: [{ type: "text", text: icoErr }], details: {} };
      }

      // Maskable PWA icon
      const maskableErr = await makeMaskable(masterPng, resolve(outDir, "icon-maskable.png"));
      if (maskableErr) {
        return { isError: true, content: [{ type: "text", text: maskableErr }], details: {} };
      }

      // Manifest
      const manifest = manifestJson({
        name: manifestName,
        shortName: params.manifestShortName ?? manifestName,
        themeColor: params.themeColor ?? "#000000",
        backgroundColor: params.backgroundColor ?? "#ffffff",
      });
      await writeFile(resolve(outDir, "site.webmanifest"), manifest, "utf8");

      const snippet = htmlSnippet(name);

      const generated = [
        `${name}.ico (multi-res 16/32/48)`,
        `${name}-16.png`,
        `${name}-32.png`,
        `apple-touch-icon.png (180×180)`,
        `icon-192.png`,
        `icon-512.png`,
        `icon-maskable.png (512×512, 80% safe-zone)`,
        `site.webmanifest`,
        ...(svgPath ? [`${name}.svg`] : []),
      ];

      return {
        content: [
          {
            type: "text",
            text: `Built favicon set in ${outDir}:\n\n${generated.map((g) => `  - ${g}`).join("\n")}\n\nHTML <head> snippet:\n\n\`\`\`html\n${snippet}\n\`\`\``,
          },
        ],
        details: { outDir, files: generated.length, name },
      };
    } finally {
      await unlink(masterPng).catch(() => {});
      const ico48 = (await import("fs/promises")).access(resolve(tmpdir(), "")).catch(() => {});
      void ico48; // no-op cleanup placeholder
    }
  },
});

export default function (pi: ExtensionAPI) {
  pi.registerTool(buildFaviconSetTool);
}
